export enum UserStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  WAITING_EMAIL_VERIFICATION = 'WAITING_EMAIL_VERIFICATION',
  WAITING_PHONE_VERIFICATION = 'WAITING_PHONE_VERIFICATION',
  WAITING_OPERATOR_VALIDATION = 'WAITING_OPERATOR_VALIDATION',
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
}
