export enum NotificationType {
  APPOINTMENT = 'APPOINTMENT',
  MARKETING = 'MARKETING',
  SECURITY = 'SECURITY',
  SYSTEM = 'SYSTEM',
}

export enum NotificationTemplateKey {
  APP_BOOKED_SUCCESS = 'APP_BOOKED_SUCCESS',
  APP_CANCELLED_BY_SALON = 'APP_CANCELLED_BY_SALON',
  APP_REMINDER = 'APP_REMINDER',

  NEW_OFFER_ALERT = 'NEW_OFFER_ALERT',
  PROMOTION_DISCOUNT = 'PROMOTION_DISCOUNT',

  WELCOME_NEW_USER = 'WELCOME_NEW_USER',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}

export enum NotificationStatus {
  READ = 'READ',
  UNREAD = 'UNREAD',
}
